### ISSUE TITLE
Display the executors used

### ISSUE THREAD

**Issue by evanfloden** [seqeralabs/nf-tower#124]
It should be possible to see on which infra each task is being run, as well as the workflow as a whole.

The hybrid / infra agnostic is big point so showing it would be important.

**Comment by pditommaso** [comment]
The idea is to add an `executor` column in the task table.

**Comment by pditommaso** [comment]
This should go as well in the *General* panel. 
<img width="518" alt="Screenshot 2019-12-16 at 12 43 23" src="https://user-images.githubusercontent.com/816968/70904743-67b28e80-2002-11ea-8f3d-7eda949962ae.png">

Also for this we would need to pick an icon https://materialdesignicons.com/

**Comment by pditommaso** [comment]
Solved by cdb7b67e.
