### ISSUE TITLE
Unexpected response code 400 for request https://api.tower.nf/trace/init

### ISSUE THREAD

**Issue by sminot** [seqeralabs/nf-tower#142]
I was able to run `nextflow run hello -with-tower` successfully, but then when I tried to use `-with-tower` on a pipeline of interest, I ran into the error:

```
N E X T F L O W  ~  version 19.09.0-edge
Pulling FredHutch/nf-viral-metagenomics ...
Already-up-to-date
Launching `FredHutch/nf-viral-metagenomics` [zen_coulomb] - revision: 94764c75f7 [master]
Unexpected response code 400 for request https://api.tower.nf/trace/init
```

It's hard for me to test all of the differences between the run that failed and the run that succeeded, but it might be helpful for me to include a slightly redacted version of the config used for the run that failed:

```
process.executor = 'awsbatch'

aws {
    region = 'us-west-2'
    batch {
        cliPath = '/home/ec2-user/miniconda/bin/aws'
        jobRole = '<>'
        volumes = ['/docker_scratch:/tmp:rw']
        maxParallelTransfers = 1
    }
}

tower {
  accessToken = '<>'
  enabled = true
}
```

Flags also included: `-process.queue`, `-with-report`, `-work-dir`, `-resume`, `-latest`, and `-with-tower`

**Comment by pditommaso** [comment]
I think, we just a found a problem with `-resume` .. thanks for reporting!

**Comment by pditommaso** [comment]
Solved
