### ISSUE TITLE
Use Bootstrap styling  for task tables

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#163]
The task table uses DataTables for interactivity, however it uses the default style set. I find this contrast with the bootstrap styling slightly jarring. I am completely aware that I am probably the _only_ person who even notices this, but still... 😅 

DataTables comes with support for Bootstrap 4 styling, see https://datatables.net/examples/styling/bootstrap4.html - so it should be possible to use this instead for a more continuous experience.

I'm currently looking into this on my fork using the [datatables.net-bs4](https://www.npmjs.com/package/datatables.net-bs4) npm package and will submit a PR when it works.

**Comment by pditommaso** [comment]
I remember we looked at this, but I was not convinced by the bootstrap layout from a visual result point of view. is it not too basic?

**Comment by ewels** [comment]
I think it looks very similar, just slightly nicer - take a look: #167 

Note that I built this on top of the mobile-styles PR, so most of the changes there are from that. I can rebase if / when the other is merged to make it cleaner.

**Comment by pditommaso** [comment]
Ok, let's postpone this after the merge of the mobile related PR. Tx!

**Comment by pditommaso** [comment]
Solved by #167.
