### ISSUE TITLE
Problem with the visualization

### ISSUE THREAD

**Issue by edgano** [seqeralabs/nf-tower#182]
Hi,
The visualization on Ubuntu + Chrome/Firefox it's not responsive

![tower](https://user-images.githubusercontent.com/4262262/67226527-754dfc80-f435-11e9-9ffa-a0e1919dba8a.png)

**Comment by pditommaso** [comment]
Maybe this is related to #184

**Comment by edgano** [comment]
Yes, it can be.
With error execution
![image](https://user-images.githubusercontent.com/4262262/67581252-011e9c00-f748-11e9-8969-2cc60611640d.png)

With an execution finish correct
![image](https://user-images.githubusercontent.com/4262262/67581325-1d223d80-f748-11e9-821f-d00de990346b.png)

**Comment by pditommaso** [comment]
Emm, yes, can upload a screen-shot of the top portion or the page. I guess the problem is there.

**Comment by edgano** [comment]
![image](https://user-images.githubusercontent.com/4262262/67767739-6f69a400-fa51-11e9-9509-c07467776e26.png)

**Comment by pditommaso** [comment]
@edgano Yesterday, we made an update to the UI. Could you please check if this is still happening?

**Comment by pditommaso** [comment]
Solved by #144 and 00e3eaee.
