### ISSUE TITLE
"Workflow execution completed unsuccessfully" can stretch the display

### ISSUE THREAD

**Issue by evanfloden** [seqeralabs/nf-tower#184]
When an error is returned as in  "Workflow execution completed unsuccessfully", it can stretch the display beyond the normal page limits.

![Screenshot 2019-10-24 12 35 22](https://user-images.githubusercontent.com/3192944/67477900-4ca74c00-f65b-11e9-8cbf-a05c46fed6d8.png)

**Comment by pditommaso** [comment]
Apparently solved by #144 and 00e3eaee. See also #182.
