### ISSUE TITLE
Use Manifest Name as top display name

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#187]
Would be nice if we could instead of `main.nf`, use the value of `workflow.name` if set.

**Comment by pditommaso** [comment]
Yeah, I was thinking the same.

**Comment by pditommaso** [comment]
Wait, but `workflow.name` is? do you mean `runName`?

**Comment by ewels** [comment]
Sorry, `manifest.name` I meant.. _i.e._ the [name of the pipeline](https://github.com/nf-core/rnaseq/blob/3b6df9bd104927298fcdf69e97cca7ff1f80527c/nextflow.config#L161) that is being run.

`runName` is already printed underneath, right?

**Comment by pditommaso** [comment]
Yep, I was thinking the same then 👍

**Comment by pditommaso** [comment]
Just thinking that showing `manifest.name` as the top name and fallback to `repo/name` when it's missing would make more sense.

**Comment by ewels** [comment]
> Just thinking that showing `manifest.name` as the top name and fallback to `repo/name` when it's missing would make more sense.

Definitely! That was my intention all along - keep the current behaviour unless `manifest.name` is present, in which case, use that..

**Comment by pditommaso** [comment]
Deal!
