### ISSUE TITLE
UI is out of sync with progress on server

### ISSUE THREAD

**Issue by aunderwo** [seqeralabs/nf-tower#192]
My work flow silly_ekeblad running using account au3@sanger.ac.uk was showing as only approximately 50% complete via the Tower UI but all except 4 tasks had completed on the CLI

![image](https://user-images.githubusercontent.com/423/68881619-5cb7c600-0705-11ea-937c-aeba224bf120.png)
![image](https://user-images.githubusercontent.com/423/68881632-62ada700-0705-11ea-88c7-4f935ed87986.png)

**Comment by aunderwo** [comment]
In the logs I see

```
WARN: Unexpected HTTP response.
Failed to send message to https://api.tower.nf -- received
- status code : 504
- response msg: Unexpected response code 504 for request https://api.tower.nf/trace/task
```

**Comment by pditommaso** [comment]
Hi Anthony, thanks for reporting this issue. Which NF version are you using? if you could upload the `.nextflow.log` that would be ideal for troubleshooting.

**Comment by aunderwo** [comment]
Thanks. 

Here is the log file
[nextflow.log](https://github.com/seqeralabs/nf-tower/files/3852072/nextflow.log)

**Comment by pditommaso** [comment]
This was due to a server temporary glitch. The only advice is to use the latest NF version that has a more resilient Tower client.
