### ISSUE TITLE
Modal for task details instead of nested table

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#206]
A quick suggestion for discussion.. What do you think about using a [bootstrap modal](https://getbootstrap.com/docs/4.4/components/modal/) window for detailed information about specific tasks instead of the nested folding table rows?

1. Currently, the nested dropdown disappears every time the table refreshes with a running workflow which is extremely annoying. By simply showing or hiding modal overlays I think we should sidestep this issue.

2. Modals would also allow the table to be a lot simpler which may facilitate more intuitive behaviour. Notably the ability to sort by any column, and making the entire table row clickable to show details.

3. With nested rows, the content expands down from wherever the row is. For me this is usually off the bottom of the screen. Modals always display in the same place and make good use of screen real-estate.

4. Finally, we could potentially organise the content a little more. For example, moving the field descriptions into tooltips and having the three tables side by side? We could hide rows with no value (eg. the cloud fields are always `-` for me). We could potentially also use [javascript tabs](https://getbootstrap.com/docs/4.4/components/navs/#javascript-behavior) to switch between sub-panels?

Phil

**Comment by pditommaso** [comment]
Hey Phil, you got a point here. We were discussing how to fix the disappearing task detail issue #200 and maybe using a dialog is the best alternative even tho it may require a separate endpoint to fetch the task detail.

For now, I would keep the table as simple as possible ie. like it is now, including the empty fields (the lack of information is still information!). 

One thing that could be nice to add is a search box that allows filtering the rows that match the searching criteria.

**Comment by ewels** [comment]
Nice 👍 Sorry, I should have spotted the existing issue.

I'm not sure that I would personally use a search box for fields in the detail view. That requires me to remember what they are called / know what I'm looking for. That makes sense for the task list table where I'm probably looking for a specific step in the pipeline. But for all of the detail fields I usually just browse.

**Comment by pditommaso** [comment]
Prototyping it. I'll ask for comments soon 😄

**Comment by pditommaso** [comment]
<img width="1420" alt="Screenshot 2019-12-11 at 13 12 49" src="https://user-images.githubusercontent.com/816968/70620593-fcd71100-1c17-11ea-8955-47e207de6041.png">

@evanfloden @ewels   What do you think? maybe it could be organised in 4 tabs: command, execution time, resources request, resource usage? Even tho, I think it's better just scrolling to see all the data instead of clicking on the tabs to switch pane. Thoughts? 
  
cc @clvadym

**Comment by ewels** [comment]
Nice! Looks great! Tabs or scrolling, either would be fine I think..

**Comment by pditommaso** [comment]
Scroll is already there. For now, should be enough.

**Comment by pditommaso** [comment]
Finally, we have the modal dialog box for the task details. @ewels as our frontend guru 😆 you may want to give a look to it 
<img width="1425" alt="Screenshot 2020-02-18 at 07 16 25" src="https://user-images.githubusercontent.com/816968/74721430-a8fc3000-5237-11ea-92d8-58cabafd100e.png">

**Comment by ewels** [comment]
Love it! 👏🏻🎉
