### ISSUE TITLE
Show Nextflow version in the General panel

### ISSUE THREAD

**Issue by MaxUlysse** [seqeralabs/nf-tower#208]
It would be a good idea to be able to have the Nextflow version used for a specific run in the tower.

**Comment by pditommaso** [comment]
The nextflow version should go in the *General* panel, after the docker container. 
<img width="518" alt="Screenshot 2019-12-16 at 12 43 23" src="https://user-images.githubusercontent.com/816968/70904516-e0fdb180-2001-11ea-8a6f-eaae91f80239.png">

The attribute is taken from `workflow.data.manifest.nextflowVersion` 

see https://github.com/seqeralabs/nf-tower/blob/30d0aa688ad6d35d73ca9086a589db27b119f136/tower-web/src/app/modules/main/entity/workflow/manifest.ts#L12

@evanfloden any idea for the icon to use for it? 

cc @clvadym

**Comment by MaxUlysse** [comment]
You should be able to to use the nextflow favicon for that (should be easy enough to svgize).

**Comment by pditommaso** [comment]
Solved by e04d2eb6.
