### ISSUE TITLE
Not able to build Tower with latest release

### ISSUE THREAD

**Issue by Z-Zen** [seqeralabs/nf-tower#218]
Since Nextflow has been updated adding new features to Tower, I wanted to try it out. 

So I pulled Tower from github however I have encoutered an issue while trying to build it.

First in dockerfile of the backend:

![image](https://user-images.githubusercontent.com/19333943/72798703-e7f09300-3c43-11ea-8136-e4504900aad1.png)

Changing it to 
```
COPY build/libs/tower-*.jar /tower/tower-backend-all.jar
```
corrected the issue and I was able to build.

When running `make run`, I get another one:

![image](https://user-images.githubusercontent.com/19333943/72798946-6b11e900-3c44-11ea-9bdc-d0e9fd2ff160.png)

Hope this helps in resolving it

**Comment by pditommaso** [comment]
The problem here was that now the backend container is not built any more from the Dockerfile but by the Gradle build script. 

https://github.com/seqeralabs/nf-tower/blob/7c5c904bff86c85c3d3519f679e632c66502047c/tower-backend/build.gradle#L131-L138

Solved by 9bed2ee2.
