### ISSUE TITLE
Invalid Exit code while process is still running

### ISSUE THREAD

**Issue by Z-Zen** [seqeralabs/nf-tower#219]
When running a Nextflow pipeline with the latest version of Nextflow-Tower, a weird code appears on the Exit column on the Nextflow-Tower page:

![image](https://user-images.githubusercontent.com/19333943/75240571-d4959200-57c4-11ea-86a0-2f068d64c803.png)

And after the process is finished:

![image](https://user-images.githubusercontent.com/19333943/75252756-948ed900-57dd-11ea-97a7-9c1325bf2bb6.png)

And this is true for any other pipelines launched.

**Comment by pditommaso** [comment]
Umm, weird. Thanks for reporting it.

**Comment by pditommaso** [comment]
Solved by 9a96627b.
