### ISSUE TITLE
Unexpected response code 403 for request

### ISSUE THREAD

**Issue by redbull05689** [seqeralabs/nf-tower#227]
I tried to run nf-tower as an on-premise installation and receive the following error:
nextflow run hello -with-tower http://nflowjbdns.eastus2.cloudapp.azure.com:8000/api
N E X T F L O W ~ version 20.01.0
Launching nextflow-io/hello [golden_shirley] - revision: 1d43afc0ec [master]
Unexpected response code 403 for request http://nflowjbdns.eastus2.cloudapp.azure.com:8000/api/trace/create
Docker-compose has the same errore.
How I. can resolve this issue?

**Comment by GHAStVHenry** [comment]
same intermittent issue here, been running for months and only just started

**Comment by pditommaso** [comment]
@GHAStVHenry We had a network failure. It's solved now. Thanks for reporting the problem.
