### ISSUE TITLE
OCD tweaks

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#229]
Hi team,

Massive kudos on the latest update - it's seriously exciting stuff! As usual my nerdy brain started spotting unimportant tiny details that no-one else cares about. I thought I'd jot them all down in a single issue as they're so minor.

I hope this is helpful! Feel free to ignore / close at your discretion.

Phil

## Launch button 🚀 

It would be cool if there was more major "Launch" button on the top nav bar, not just in the dropdown. I feel like this is now one of the main CTA features for the site, eg:

<img src="https://user-images.githubusercontent.com/465550/82925607-39a48380-9f7e-11ea-96a6-0ff4f47d33f0.png" height=150>

Maybe don't show it until some credentials / a compute environment has been set up? That way it won't bother people who only want to use tower for monitoring workflows.

## Inconsistent capitalisation:

<img src="https://user-images.githubusercontent.com/465550/82925097-8fc4f700-9f7d-11ea-9cb6-9142c97ae84b.png" height=200>

(Should be _Compute environments_, _Manage credentials_). Same goes for page titles.

Personally I prefer everything to be _Sentence case_, with just the first word. But each to his own.

## Page consistency

The styling of the `/welcome` pages feels increasingly inconsistent as more pages are added. Also, the _Compute_ and _Credentials_ pages have the page title and intro in a `.card` but _Profile_ and _Tokens_ don't.

## Edit credentials

I was kind of expecting to be able to edit, or at least view more details of credentials once added. Especially because the title is styled in blue, like a link:

<img src="https://user-images.githubusercontent.com/465550/82925806-8e47fe80-9f7e-11ea-9fd5-383d192b8a30.png" height=200>

## Config params help text

I think @evanfloden said on a call that this field takes any Nextflow config - the help text needs to say what format the parameters are expected in at least.

<img src="https://user-images.githubusercontent.com/465550/82926448-7fae1700-9f7f-11ea-84dc-21c1468bc1f2.png" height=100>

**Comment by pditommaso** [comment]
> As usual my nerdy brain started spotting unimportant tiny details that no-one else cares about

I love this kind of feedback! 

> Launch button

👍 

> Inconsistent capitalisation

👍 

> Page consistency

You are right, not very soon, but the plan is to restyle all the look & feel using a more consistent design system eg. [Primer](https://github.com/primer/css) or [Carbon](https://www.carbondesignsystem.com/). If you know others, let us know.  

> Edit credentials

This was done on purpose, mainly to avoid to expose creds over API for security reasons. I agree that the blue title can be confusing. 


> Config params help text

True, tho I thought that also *Config profiles* should become "Nextflow (config) profiles". it's not a bit redundant repeating *nextflow* in all fields? at the end, it's also mentioned in the hint text.

**Comment by ewels** [comment]
> You are right, not very soon, but the plan is to restyle all the look & feel using a more consistent design system eg. Primer or Carbon. If you know others, let us know.

Nice! How is this different to [Bootstrap](https://getbootstrap.com/), that you're currently using?

I think that the Bootstrap components that you're currently using are fine - you just need to decide which set you want to use and stick with them. For bigger sites I usually enforce this by writing a basic style guide for the different people writing content (or just looking over the site and pointing out inconsistencies as above). Switching CSS framework at this point sounds like a lot of work..

> Edit credentials

Yup I figured, as you say it was the blue text that threw me though. I guess if you wanted it to click through to something, you could show some meta (eg. when it was created) and some `***` for the sensitive data? Or yeah, just remove the blue text 👍 

> Config params help text

I think just adding _Nextflow_ doesn't help much and is a bit redundant as you say. Nextflow parameters can be supplied in config files, in JSON files and on the command line - they are all Nextflow _config params_. This is the distinction that I was looking for. Finding a good wording for it is tricky though! Maybe the hint text could just add _with the syntax used in `nextflow.config`_  or something to make it clearer? Don't know..

**Comment by pditommaso** [comment]
> Nice! How is this different to Bootstrap, that you're currently using?

[Primer](https://primer.style/css/) for example has many more controls and resulting layout look more stable and professional. It's the one used by GitHub!  I agree that it can require a considerable work. In the short term we are surely remaining with Bootstrap. 

> Yup I figured, as you say it was the blue text that threw me though

Yeah, we need to address this

**Comment by ewels** [comment]
Is there anything specific in Primer that you're thinking of that Bootstrap is missing? Asking purely out of curiosity 😅 I've  never really heard of it before - casting my eye down the list of components I was thinking that it looked strikingly similar to Bootstrap's components (hence my question), but maybe I'm missing stuff? The [Timeline](https://primer.style/css/components/timeline) component looks cool 🤩 That's the only one I could see that Bootstrap doesn't do. Oh and the [Animations](https://primer.style/css/utilities/animations) are kind of nice.

Thinking of other alternatives that I know of, [Zurb Foundation](https://get.foundation/) has been around for years and I've used on quite a few sites. It's the only alternative to Bootstrap that I've ever used seriously. Oh and there's the Google-style [Materialize](https://materializecss.com/) if that's your thing. There are hundreds kicking around these days though - most seem to work in much the same way though so I think it mostly comes down to which style you like the best.

I didn't find a side-by-side comparison of component types that I was looking for, but [this review of frameworks](https://www.lambdatest.com/blog/best-css-framework-2020/) is fairly recent and lists a lot.

**Comment by pditommaso** [comment]
Also [autocomplete](https://primer.style/css/components/autocomplete), [dropdown](https://primer.style/css/components/dropdown), [popover](https://primer.style/css/components/popover), [toast](https://primer.style/css/components/popover) components are quite useful. 

I'm quite sure there are similar components also in Boostrap, however, what's convincing more is that Primer looks having a more consistent UI experience and better typography.

**Comment by ewels** [comment]
You've peaked my curiosity now 😆 

Bootstrap equivalents: [dropdown](https://getbootstrap.com/docs/4.5/components/dropdowns/), [popover](https://getbootstrap.com/docs/4.5/components/popovers/), [toasts](https://getbootstrap.com/docs/4.5/components/toasts/). Autocomplete looks nice, especially as it comes with an associated npm package. There are [bootstrap plugins](https://raw.githack.com/xcash/bootstrap-autocomplete/master/dist/latest/index.html) to do the same, but nothing bundled with the core library that I'm aware of.

The [Primer typography](https://primer.style/css/utilities/typography) looks basically identical to [Bootstrap typography](https://getbootstrap.com/docs/4.5/content/typography/)? Or how do you mean?

**Comment by ewels** [comment]
For the record, I love _all_ CSS kits. I still remember when the [960 grid](https://960.gs/) came out way back when, totally changed how I built websites!

**Comment by pditommaso** [comment]
Yes, also Boostrap has more or less the same components but IMO the Prime ones look more curated. For example the dropdown: 

<img width="215" alt="Screenshot 2020-06-01 at 10 24 51" src="https://user-images.githubusercontent.com/816968/83390567-5d3e5280-a3f2-11ea-837b-8cf149631d09.png">

<img width="269" alt="Screenshot 2020-06-01 at 10 25 06" src="https://user-images.githubusercontent.com/816968/83390583-64656080-a3f2-11ea-8e25-fe07003136bf.png">

Small differences like the button border, the shadow, etc make it appears the Prime components more professional. 

Same for the font, you are right about that, but still, the final result looks more clean and readable to me. Either I'm biased because used to GitHub style or the combination of colors, spaces, etc makes the final result better (or both 😄).

**Comment by ewels** [comment]
You can add class `shadow` to the dropdown `ul` if you like that 😉 

<img src="https://user-images.githubusercontent.com/465550/83395778-32a4c780-a3fb-11ea-84c7-b120b618ad7b.png" width=250>

The Primer button styles look a bit like the Bootstrap v2 buttons, some of the [Bootswatch](https://bootswatch.com/) themes have a similar feel too.

But yeah, I get the point.. 😉 I think the look and feel of GitHub / Primer is really nice, and a lot of users will be familiar with that UI kit.

I guess my only point is that you can get a long way by customising Bootstrap, which avoids you having to completely rewrite the entire front-end of the site.

**Comment by pditommaso** [comment]
You are right as well, it's a trade-off and nothing is decided yet at this respect. Just evaluating alternatives. Nice the Bootswatch themes, I'm adding to the list.

**Comment by ewels** [comment]
Yup, there are tonnes of Bootstrap themes kicking around (see eg. [Theme Forest](https://themeforest.net/search?compatible_with=Bootstrap), or just google "Bootstrap themes" - there are hundreds dedicated sites for this).

https://themes.getbootstrap.com/ is worth a mention - it's curated by the Bootstrap authors and the themes usually come with quite a few additional components.

**Comment by pditommaso** [comment]
- [x] Launch button
- [x] Inconsistent capitalisation
- [x] Edit credentials (replaced title style to avoid confusion) 
- [x] Config params help text (added refence to nextflow.config file) 

Thanks Phil!

**Comment by ewels** [comment]
Nice! 👏 Thanks!

**Comment by ewels** [comment]
Just had a look - much better 🚀
