### ISSUE TITLE
Dark mode favicon

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#230]
Using Chrome with Dark-mode in OSX, the black favicon is pretty much invisible:
<img src="https://user-images.githubusercontent.com/465550/82927382-ef70d180-9f80-11ea-87e1-5538b9b88c72.png" height=50>

It would be ace if the website could use a white favicon instead for users running dark mode.

You should be able to use the new `prefers-color-scheme` CSS selector to have different favicons according to whether the user is using dark mode or not:

```html
<link rel="icon" href="/favicon.ico?light" media="(prefers-color-scheme:no-preference)">
<link rel="icon" href="/favicon.ico?dark"  media="(prefers-color-scheme:dark)">
<link rel="icon" href="/favicon.ico?light" media="(prefers-color-scheme:light)">
```

As it's pretty trivial and unimportant and degrades gracefully, I'm not sure that you need much more. Snippet come from [this SO post](https://stackoverflow.com/a/58551905/713980) which has more details and a JS implementation if you want extra compatibility though.

**Comment by pditommaso** [comment]
Cool 👍

**Comment by pditommaso** [comment]
Umm, we have fixed this not now it's white! same as github :D What am I missing? cc/ @ynestin 

<img width="813" alt="Screenshot 2020-08-04 at 10 10 34" src="https://user-images.githubusercontent.com/816968/89270180-45c25680-d63b-11ea-8671-ad65b12d9df2.png">

**Comment by ynestin** [comment]
What do you mean exactly? 😄

**Comment by ewels** [comment]
Nice! The GitHub favicon is white for you because you’re in dark mode. If you switch to light mode then it will be black :)

**Comment by pditommaso** [comment]
But black would be more visible! 😄  not understanding from where your screenshot come from?

**Comment by ynestin** [comment]
@pditommaso Do you mean this issue was fixed before https://github.com/seqeralabs/nf-tower-cloud/pull/339?

**Comment by pditommaso** [comment]
I think I've understood, it's my chrome theme that messes up things. Opening in guest mode with no theme it's fine. 
<img width="730" alt="Screenshot 2020-08-04 at 10 29 12" src="https://user-images.githubusercontent.com/816968/89271847-92a72c80-d63d-11ea-9af0-88d41c510fc1.png">

**Comment by pditommaso** [comment]
Done!
