### ISSUE TITLE
Cost miscalculation

### ISSUE THREAD

**Issue by hnawar** [seqeralabs/nf-tower#235]
Some tasks seem to have miscalculated cost on GCP
A task I had ran for 2 h 9m (duration) the time in resources required was 10 h the instance type was n1-highcpu-16 in europe-west2 with 500GB disk
The calculated 5.1388 USD which seems closer to this instance running for 9 hours rather than 2 h 9m
![task cost-nftiwer](https://user-images.githubusercontent.com/16020853/84696585-a7701980-af44-11ea-814f-2f482bf870ab.png)

**Comment by pditommaso** [comment]
That's weird. Could you please provide the ID of this run?

**Comment by hnawar** [comment]
Run ID was suspicious_swirles
This task was the metaphlanOnly

**Comment by pditommaso** [comment]
I mean the alphanumeric ID, sorry. 

<img width="533" alt="Screenshot 2020-06-15 at 21 23 28" src="https://user-images.githubusercontent.com/816968/84697481-7bf22c80-af4e-11ea-80e1-21f7c52aa125.png">

**Comment by hnawar** [comment]
5r4vxmbw

**Comment by pditommaso** [comment]
Coping here for reference 

|id      |task_id|name                                   |realtime|duration|cpus|time    |cost        |price_model|machine_type |
|--------|-------|---------------------------------------|--------|--------|----|--------|------------|-----------|-------------|
|60652754|9      |metaphlanOnly (metaphlan2 ERR3645029)  |10024382|10296966|16  |36000000|6.8634627596|standard   |n1-highcpu-16|
|60652755|10     |metaphlanOnly (metaphlan2 ERR3450621)  |9402123 |9679488 |16  |36000000|6.4376199829|standard   |n1-highcpu-16|
|60652753|11     |metaphlanOnly (metaphlan2 ERR3450658)  |5780863 |6036550 |16  |36000000|3.9578731385|standard   |n1-highcpu-16|
|60652756|12     |metaphlanOnly (metaphlan2 ERR3450790)  |8755537 |9036066 |16  |36000000|5.9946613390|standard   |n1-highcpu-16|
|60652757|13     |metaphlanOnly (metaphlan2 ERR3450841)  |7505966 |7775495 |16  |36000000|5.1388679774|standard   |n1-highcpu-16|
|60658177|14     |mergeMetaphlanOnly (metaphlan2 merging)|69      |168844  |2   |14400000|0.0000423372|standard   |n1-highmem-2 |

**Comment by hnawar** [comment]
Is this duration in seconds? if so then this may be what is wrong, this is the duration as per the execution trace


9 | metaphlanOnly | metaphlan2 ERR3645029 | 2 h 51 m 37 s | 2 h 47 m 4 s
10 | metaphlanOnly | metaphlan2 ERR3450621 | 2 h 41 m 19 s | 2 h 36 m 42 s
11 | metaphlanOnly | metaphlan2 ERR3450658 | 1 h 40 m 37 s | 1 h 36 m 21 s
12 | metaphlanOnly | metaphlan2 ERR3450790 | 2 h 30 m 36 s | 2 h 25 m 56 s
13 | metaphlanOnly | metaphlan2 ERR3450841 | 2 h 9 m 35 s | 2 h 5 m 6 s
14 | mergeMetaphlanOnly | metaphlan2 merging | 2 m 49 s | 0 s

**Comment by pditommaso** [comment]
No, the time is in millis. However I found the problem, it's actually a bug. 

It's caused by the fact we consider also the memory to estimate how much *slots* the job is consuming. If the instance has 16G and the task requires 8GB, the job is expected to cost half because another job could potentially be allocated in that WM (but, yes, it should also be considered that Google LS maps 1 container to 1 WM, therefore does not make much sense). 

In this case, the job requires 48 GB and the VM provides 14 GB and therefore the unit cost is multiplied by ~ 3.4 which does not make sense at all. 

Thanks for having spotted that.

**Comment by pditommaso** [comment]
This was solved. Thanks for reporting it.
