### ISSUE TITLE
See .command.err or .command.log in the interface

### ISSUE THREAD

**Issue by GuillaumeTh** [seqeralabs/nf-tower#236]
First, congrats for this beautiful interface. Very useful.

It could be nice to see the .command.err or .command.log in the interface when you click on a task for example.

**Comment by pditommaso** [comment]
> First, congrats for this beautiful interface. Very useful.

Thanks! 

> It could be nice to see the .command.err or .command.log in the interface when you click on a task for example.

Indeed. On-going development actually. Stay in touch.

**Comment by GuillaumeTh** [comment]
Cool ! Thanks for this ! Do I close the issue ?

**Comment by pditommaso** [comment]
This is available in tower.nf.
