### ISSUE TITLE
Launch - nicer ANSI colours

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#237]
The current rendering of ANSI colours from the launch console output works well, but the colours are a bit crap - at least for the nf-core ANSI logo:

![image](https://user-images.githubusercontent.com/465550/85013483-f09eb400-b164-11ea-917f-f4339a7c1962.png)

I guess that the colours used are the [original ANSI set](https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit) from the 70s. I think that a nicer colour scheme could help readability.

@pditommaso said that you guys are using the [ansi-to-html](https://www.npmjs.com/package/ansi-to-html) package for this, and I can find that in `package.lock`. However, I can't find where it's actually being used in the code anywhere?

Anyway, according to the docs for that package, the colours can be overridden:

> **colors** `Object/Array` (with values 0 - 255 containing CSS color values). Can override specific colors or the entire ANSI palette

Based on the wikipedia page linked above, I made a JSON block with the 3/4 ANSI codes and HEX colours from the _Visual Studio Code Debug Console (Default Dark+ Theme)_:

```json
{
    "30": "#000000",
    "31": "#cd3131",
    "32": "#0dbc79",
    "33": "#e5e510",
    "34": "#2472c8",
    "35": "#bc3fbc",
    "36": "#11a8cd",
    "37": "#e5e5e5",
    "90": "#666666",
    "91": "#f14c4c",
    "92": "#23d18b",
    "93": "#f5f543",
    "94": "#3b8eea",
    "95": "#d670d6",
    "96": "#29b8dB",
    "97": "#e5e5e5",
    "40": "#000000",
    "41": "#cd3131",
    "42": "#0dbc79",
    "43": "#e5e510",
    "44": "#2472c8",
    "45": "#bc3fbc",
    "46": "#11a8cd",
    "47": "#e5e5e5",
    "100": "#666666",
    "101": "#f14c4c",
    "102": "#23d18b",
    "103": "#f5f543",
    "104": "#3b8eea",
    "105": "#d670d6",
    "106": "#29b8dB",
    "107": "#e5e5e5"
}
```

This is very much a stab in the dark, I have no idea if this will work or not. But could be nice if so!

Opportunities exist for getting fancier if the concept works: https://mayccoll.github.io/Gogh/

Phil

**Comment by pditommaso** [comment]
Solved on tower.nf.
