### ISSUE TITLE
API for Public Use

### ISSUE THREAD

**Issue by mshamash** [seqeralabs/nf-tower#238]
Hello,

I'm writing to inquire about the status of an API for Nextflow Tower so that developers may use it to inquire on running job status, completion, errors, etc. I'm hoping to use something like that to create an in-house system for monitoring our Nextflow tasks running on HPC.

Thanks.

**Comment by pditommaso** [comment]
Hi, thanks for your interest in the project. We need to finalize the API before making it public. I'll post any update at this regard here.

**Comment by pditommaso** [comment]
Available at this link 
https://tower.nf/openapi/index.html
