### ISSUE TITLE
Bot security issue

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower#244]
It looks the security bot is still not happy. 

https://github.com/seqeralabs/nf-tower/network/alert/tower-web/package-lock.json/npm-registry-fetch/open

@ynestin Could you please give it a look?

**Comment by ynestin** [comment]
@pditommaso Could you please send me a screenshot of the issue? I still get the 404 error when trying to open the following link.

> https://github.com/seqeralabs/nf-tower/network/alert/tower-web/package-lock.json/npm-registry-fetch/open

**Comment by pditommaso** [comment]
Ouch, I was thinking it was public accessible

**Comment by pditommaso** [comment]
This 👇 
<img width="1059" alt="Screenshot 2020-08-25 at 09 25 52" src="https://user-images.githubusercontent.com/816968/91144939-01176180-e6b5-11ea-9156-0208aae512f7.png">

**Comment by ynestin** [comment]
@pditommaso I have made my investigation and to fix the above package vulnerability issue we will have to update at least to Angular 8 latest version (from `8.1.1` to `8.2.14`). Would it be ok for you?

**Comment by pditommaso** [comment]
I dont know, it's the GitHub bot complaining 😆. Let's try.

**Comment by pditommaso** [comment]
Wait, are not already with Angular 9?

**Comment by ynestin** [comment]
> Wait, are not already with Angular 9?

On `nf-tower-cloud` repository we are but here it is still Angular 8

**Comment by pditommaso** [comment]
Can you try to see how much is the impact to upgrading to 9 also this repo?

**Comment by ynestin** [comment]
Let me check. There should not be too many changes. Also, updating to the latest Angular 8 version is a sub-step of migrating to Angular 9 so we are already halfway through
