### ISSUE TITLE
Add the line continuation marker in the Command-Line section

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower#251]
Hi team,

It's a really nice feature to be able to see the command used to invoke `nextflow` in `tower`!

![image](https://user-images.githubusercontent.com/12799326/94516132-c0c27a80-0242-11eb-8a6b-2bdd53adbd7b.png)

I think that perhaps reusability of the command can be improved with the addition of a line separator 

```
nextflow run bwa.nf \
		 -with-trace bwa_mem_trace.txt \
		 -with-tower \
		 --mem

```

I can see the use case of sharing the execution page with a collaborator and then just pointing them to the command which was used to invoke the pipeline, they could _ideally_ simply copy and paste the command mentioned in `tower.

**Comment by pditommaso** [comment]
We have added a copy button which container the CLI formatted shell friendly 😉

**Comment by abhi18av** [comment]
This works just as well 👍
