### ISSUE TITLE
Multi-day sessions for improved user experience

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower#254]
Hi team,

I've been using `tower` extensively and I was wondering whether it'd be possible to add a multi-day session option so as to avoid logging in everyday, this might improve the user experience.

It could be something as simple as 

```
[ ]  Remember me for 7 days

```

**Comment by pditommaso** [comment]
In the pipeline! 👍

**Comment by abhi18av** [comment]
Thanks 👍
________________________________
