### ISSUE TITLE
Is it possible to configure pipeline sharing?

### ISSUE THREAD

**Issue by Midnighter** [seqeralabs/nf-tower#255]
Hi,

I love the new pipeline sharing feature on tower.nf! Many thanks for that :heart: 

I was wondering if it is possible to somehow configure who I want to share pipelines with more permanently? Similarly to the token, I would ideally like to be able to put this in my local configuration since that is typically how I launch pipelines. So it could look like:

```groovy
tower {
  enabled = true
  accessToken = '14fee934bbcaa30b673b555e70a4440cfb0a61ae'
  collaborators = ['co-worker_github', 'co-worker_google']
}
```

**Comment by pditommaso** [comment]
This a nice idea, but I fear that would make config files less portable. The plan is to have a more systematic sharing experience with Team feature on which we are working.
