### ISSUE TITLE
Workflow deletion does not require confirmation

### ISSUE THREAD

**Issue by klmr** [seqeralabs/nf-tower#256]
When clicking on the rubbish bin icon next to a workflow, a dialog pops up that says “Please confirm the deletion of workflow 'adjective_name' typing its name below (operation is not recoverable):”, and the “Confirm” button is disabled.

However, hitting the “Return” key on the keyboard without entering anything closes the dialog *and deletes the workflow*.

**Comment by pditommaso** [comment]
Ouch! Thanks for reporting! cc @ynestin  ☝️

**Comment by pditommaso** [comment]
Solved.
