### ISSUE TITLE
Error creating an environment with strategy SPOT_CAPACITY_OPTIMIZED

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#262]
Just got this error when creating a new environment with forge:

`
Error executing request, Exception : Invalid compute resource allocation strategy SPOT_CAPACITY_OPTIMIZED for type EC2, RequestId: ******* (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: ****; Proxy: null)
`

_(I can provide the request ID if needed)_

As you can probably guess from the error message, I selected `SPOT_CAPACITY_OPTIMIZED` as the ***Allocation strategy*** in the advanced setting (even though I'm not really sure what it does).

I tried again but left that field as the default, and the environment was created successfully.

**Comment by pditommaso** [comment]
I guess you have chosen *On-demand* provisioning. Allocation strategy only works for *SPOT*. 

But I agree the UI should guide the user.

**Comment by ewels** [comment]
Nope, this was with Spot provisioning..

**Comment by pditommaso** [comment]
Ouch, got it as well. Good now, I can test it.

**Comment by pditommaso** [comment]
Solved
