### ISSUE TITLE
Error creating an environment: Allowed S3 buckets not saved

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#263]
The field ***Allowed S3 buckets*** doesn't seem to be saved when creating a new AWS compute environment. I filled in this field but when viewing the environment after creation it is blank:

![image](https://user-images.githubusercontent.com/465550/98111600-212b8400-1ea1-11eb-80eb-f20b619ab8c6.png)

**Comment by pditommaso** [comment]
Unable to replicate. Are you sure the bucket was properly selected, it should render as a blue badge 
<img width="1045" alt="Screenshot 2020-11-04 at 16 02 35" src="https://user-images.githubusercontent.com/816968/98127703-4925e200-1eb7-11eb-8720-4d01b660786d.png">

**Comment by ewels** [comment]
Ah, no - I pasted it in and it was just text. The other place to enter the s3 bucket is just raw text input and I didn't notice the help text sorry.

I have made this same mistake with config profile names several times. Could the UI prevent form submission if there is text in these inputs that hasn't been converted into a tag like this?

**Comment by pditommaso** [comment]
> Could the UI prevent form submission if there is text in these inputs that hasn't been converted into a tag like this?

Yes, this is reasonable. @ynestin could you give a try ?

**Comment by ynestin** [comment]
Sure, will check.

**Comment by ewels** [comment]
I just watched @drpatelh and @MaxUlysse make this same mistake with the config profiles over a Zoom call - so it's not just me! 😅

**Comment by drpatelh** [comment]
Yup. I had to manually delete the S3 bucket, start again and make sure I pressed "Enter". 

On a side note, I have to say all of this Tower job submission to AWS is might impressive when you have set up the correct credentials! Good work guys :bowtie:

**Comment by ggabernet** [comment]
yes, it happened to me as well when filling up the `profile` field the first time 😅 

We had a tower launch session, sharing the pipeline runs was awesome!

**Comment by pditommaso** [comment]
Done
