### ISSUE TITLE
Page doesn't update when deleting a compute environment

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#264]
When deleting a compute environment, I typed `CONFIRM` and clicked submit and the modal disappeared. However, the list of compute environments did not update and the old environment was still shown. No success message was shown and the page didn't refresh.

If I manually refreshed the page then the environment is gone, so the deletion works fine.

**Comment by pditommaso** [comment]
Weird, could you check in the brower console log?

**Comment by ewels** [comment]
Console looks clear:

![image](https://user-images.githubusercontent.com/465550/98130532-a4a59f00-1eba-11eb-9f1d-f4b70b27be57.png)

This is what I see:

![Nov-04-2020 16-26-29](https://user-images.githubusercontent.com/465550/98130429-86d83a00-1eba-11eb-9c95-9c8bf1ad3bfe.gif)

I can keep deleting it as many times as I like as long as I don't refresh the page and it doesn't throw an error.

**Comment by pditommaso** [comment]
Have you access to backend logs?

**Comment by ewels** [comment]
I've asked IT, but not immediately no.

I just tried to replicate this on https://tower.nf but it worked fine:

![Nov-04-2020 19-54-20](https://user-images.githubusercontent.com/465550/98156086-974add80-1ed7-11eb-8f34-d123f28fe4d0.gif)

So I guess that this issue is limited to our local installation...

**Comment by ewels** [comment]
As this is local and not easy for me to find the back end logs, plus it is _such_ a minor issue, I don't think that I can be bothered to chase this 😅 

As it's working fine on tower.nf then I'm happy 😄
