### ISSUE TITLE
Feature request: Allow users to execute a stub-run for nextflow pipelines using tower

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower#270]
Following up from the conversation here https://github.com/nextflow-io/nextflow/pull/1804 

I understand that locally, the `-stub` command be run using the `nextflow-edge run process.nf -entry test -stub` which helps the users to make sure the channel IO is working fine. 

However, could this facility be also integrated to Tower? I think it could provide users a faster feedback loop.

**Comment by pditommaso** [comment]
Done
