### ISSUE TITLE
Feature request: Massive warning if min cpus > 0

### ISSUE THREAD

**Issue by ewels** [seqeralabs/nf-tower#274]
So looks like we accidentally burnt a few AWS credits by setting up an AWS environment via Tower and setting the _"Min vCPUS"_ to something greater than 0. This meant that we had some EC2 instances just sat there doing nothing for a while. Luckily we noticed fairly quickly.

I imagine that most people most of the time will want this setting to be 0. The side effects of having it > 0 can be quite expensive! Could Tower give a massive huge warning explaining this if you try to create a new environment with this set to > 0 please?

My future-me thanks you in advance! 😅

**Comment by pditommaso** [comment]
Yes, you are right. I think we should even remove it or move to the advanced settings with the big warning.

**Comment by pditommaso** [comment]
The min CPUs, has been moved to advanced option and a warning is shown when specifying anything > 0. 

Thanks for reporting this!

**Comment by ewels** [comment]
Brilliant - thanks!
