### ISSUE TITLE
How to use /trace endpoint in API

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#280]
I would like to repeatedly query the status of a workflow running on tower through its API.

I guess the best endpoint is `/trace` but I don't understand its logic. Do I have to create a trace first, or can I directly use eg "heartbeat" for this?

Any (pseudo) example would be greatly appreciated!

Kind regards

**Comment by pditommaso** [comment]
The /trace requests are used by NF to submit the workflow execution progress. I think what you are looking for is returned by the GET `/workflow/{id}` API 

https://tower.nf/openapi/index.html#get-/workflow/{workflowId}

Check the status field.

**Comment by phiweger** [comment]
ah ok so /trace is the wrong endpoint for this thx!6
