### ISSUE TITLE
Missing Xpack-amzn license - Make sure to have the variable NXF_XPACK_LICENSE defined in your environment

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#282]
I launched a wf via the API that ran without any errors just yesterday, and today (same setup, same input) it fails and I read this in the error log:

```
Missing Xpack-amzn license - Make sure to have the variable NXF_XPACK_LICENSE defined in your environment
```

What is the source of this error?

Thanks!

**Comment by phiweger** [comment]
I noticed one difference: When it used to work, tower displayed the command with the github path in 'quotes':

```
nextflow run 'https://github.com/phiweger/mock_pe.git'
...
```

Now (failing) the quotes are missing:

```
nextflow run https://github.com/phiweger/mock_pe.git
...
```

**Comment by pditommaso** [comment]
Hello, can you provide the ID of a failing execution ?

**Comment by phiweger** [comment]
@pditommaso sure:

Those did not work:

- 5X3PgYHg1Pj91k
- 2zpGuI1Ui0Et5y
- 2pXAbVgVE4eBe2

Those went through earlier (same workflows):

- 45YyuKAjTERXHr
- 1FUqdAGZLWlGA5

Thanks for looking into this!

**Comment by pditommaso** [comment]
We have identified the problem, I'll let know when fixed.

**Comment by pditommaso** [comment]
Problem solved. Sorry for the incovenienec and thanks for reporting the issue!
