### ISSUE TITLE
Confused about "region" and "location" settings in Compute Environment

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#284]
The explanation given under the fields in the compute env settings is

- region .. The region where the workload will be deployed
- location .. The location where Life Sciences API runs

Now Google seems to know regions like "europe-west1" and zones like "europe-west1-a" but what is a "location"?

It seems like the most sensical thing is to set them both to the same thing, eg "europe-west1-a", right?

Thank you for clarification!

**Comment by alaincoletta** [comment]
Hi @phiweger, the Cloud Life Sciences uses *Regional Locations*, for each Location there can be more than one region. 
You can read more about these concepts here:
https://cloud.google.com/life-sciences/docs/concepts/locations
