### ISSUE TITLE
Tower is very slow compared to local nf instance executing in the cloud

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#286]
I have a simple wf that just trims some adapters off Illumina data.

The Tower compute environment is in the same Google region as the workdir bucket, which is at the same time the bucket that already contains the input data (ie no time for staging is required).

However, when I launch nextflow on my laptop and have the workflow execute in the cloud, it takes like 10 min max. __When I use the Tower API, it's really slow (> 1 h sometimes).__

One example of such a run has the Tower ID `2uP7NvEcn6AKIo`

I am sure I am missing a bottleneck somewhere, you help is greatly appreciated!

**Comment by phiweger** [comment]
It seems that it takes a disproportionate time to clean up after process execution, see this timeline report from another run:
<img width="931" alt="Screenshot 2021-02-04 at 11 55 16 AM" src="https://user-images.githubusercontent.com/3918306/106883139-e293a880-66df-11eb-950c-20db1c1bf688.png">

**Comment by pditommaso** [comment]
It may be due to too little resources for the head nextflow job. Increase the cpus and mem in the advanced settings.

**Comment by phiweger** [comment]
Thanks @pditommaso for the quick response!

I tried with a boot disk size of 50 gb, 8 cpu and 16 gb memory, and saw no difference. This should suffice for the head nf job right?

**Comment by pditommaso** [comment]
> This should suffice for the head nf job right?

I would say so, can you share the .nextflow.log file produced by the execution ?

**Comment by phiweger** [comment]
You are right it seems to be a resource issue on my end, ie limitations on the total number of CPUs I can use. I will investigate and report thx!

**Comment by phiweger** [comment]
@pditommaso you were right I increased the resources available to the whole execution (ie the cumulative number of cpus allowed) and it now runs as expected, many thx!

**Comment by pditommaso** [comment]
Excellent. I guess in the GCP settings, right?

**Comment by phiweger** [comment]
Yes @pditommaso I needed to up the allowed quota to get a higher (cumulative) number of cpus.
