### ISSUE TITLE
Does .collectFiles() work on GCP?

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#287]
When I include any process with `.collectFiles()` such as

```
qc.out.map { name, qc -> qc }.collectFile(name: "${params.results}/qc.txt", newLine: true, keepHeader: true)
```

then Tower fails with

```
Cannot a find a file system provider for scheme: gs
```

Why is that? Thanks for the support!

**Comment by pditommaso** [comment]
Which platform are you deploying the execution?

**Comment by phiweger** [comment]
I use the Tower API to launch the wf on the the Google Life Science platform ("google-lifesciences").

**Comment by pditommaso** [comment]
Can share a minimal test replicating the problem, possible via a small GitHub project?

**Comment by phiweger** [comment]
Sure @pditommaso :

https://github.com/phiweger/covid_mock

**Comment by pditommaso** [comment]
I was giving a try to this, but I can't see reference to any gs bucket. Could you provide a configuration that I can test?

**Comment by phiweger** [comment]
You have to add any bucket that you have rights to [here](https://github.com/phiweger/covid_mock/blob/main/input.csv#L1).

**Comment by pditommaso** [comment]
Ok, problem solved. Thanks for your feedback.
