### ISSUE TITLE
Define zones instead of region

### ISSUE THREAD

**Issue by phiweger** [seqeralabs/nf-tower#288]
In my config profiles I am used to write something like this when using nextflow (local instance) with cloud execution (google life science api on GCP):

```
        google { 
            lifeSciences.preemptible = false
            lifeSciences.bootDiskSize = 50.GB
            zone = 'europe-west3-a,europe-west3-b,europe-west3-c'
        }
```

However, on Tower, when I configure a compute env, I can only set a __region__, not a __zone__, ie I cannot specify "europe-west3-a" in the Tower compute env configuration. Neither can I do this in the `nextflow.config` bc/ then I get an error saying that I need to specify either region or zone, not both.

How can I supply multiple zones to Tower for the wf execution?

**Comment by pditommaso** [comment]
I think currently there's no support for it. A good point to add it.

**Comment by replikation** [comment]
nice. zones have unlimited resource access. regions are quite restricted currently (for google cloud)

**Comment by pditommaso** [comment]
The ability to specify one or more zones has been added. 

<img width="1066" alt="Screenshot 2021-02-17 at 09 46 15" src="https://user-images.githubusercontent.com/816968/108178676-00f89b80-7105-11eb-9a19-5f526fe4c751.png">

**Comment by replikation** [comment]
nice thank you.

**Comment by phiweger** [comment]
awesome @pditommaso !
