### ISSUE TITLE
Testing of New Pipeline Launchpad

### ISSUE THREAD

**Issue by ggabernet** [seqeralabs/nf-tower#296]
Hi all,

I've tried to test the teams and much anticipated Pipeline Launchpad but there seems to be an issue when specifying the pipeline name, I've tried different options but always get:

![Screenshot 2021-04-12 at 14 55 08](https://user-images.githubusercontent.com/3973503/114397695-3cf92b80-9b9f-11eb-8c55-5104a0a587c6.png)

**Comment by pditommaso** [comment]
Try all lowercase.

**Comment by pditommaso** [comment]
and `-` instead of `_`

**Comment by ggabernet** [comment]
Thanks, that worked now! Starting some tests :)

**Comment by pditommaso** [comment]
Wait! I'm going to release a new version in 5 mins. is it fine for you?
