### ISSUE TITLE
Zombie run

### ISSUE THREAD

**Issue by lucdh** [seqeralabs/nf-tower#313]
We have a run for which all resources have been killed, but that after several days is still shown as active in the nf-tower console.  The delete icon for this run is disabled. Is there another way to force the removal of this project from the list?

**Comment by pditommaso** [comment]
Has it been launched from nextflow command line or via tower UI ?

**Comment by lucdh** [comment]
It was launched and killed from the command line.

**Comment by pditommaso** [comment]
Can you please please report the workflow id as it shown in the Tower console ?

**Comment by lucdh** [comment]
KwbWKWn8kGJfH

**Comment by pditommaso** [comment]
It should be solved now.

**Comment by lucdh** [comment]
indeed, thank a lot!

**Comment by pditommaso** [comment]
Nice 👍
