### ISSUE TITLE
Task submitted but not starting from 2 days..

### ISSUE THREAD

**Issue by varun171** [seqeralabs/nf-tower#314]
I started two pipelines and it has been more than 24 hours and I do not see that task is running. .Only tasks were summited and then no progress. Can someone suggest if I should relaunch or wait.

**Comment by pditommaso** [comment]
Hello, have you specified spot instances and/or some specific instance types. Your request may not be fulfilled by the AWS avail resources.

**Comment by varun171** [comment]
> Hello, have you specified spot instances and/or some specific instance types. Your request may not be fulfilled by the AWS avail resources.

Thanks, I figured out the issues and yes it was related to instance type.
