### ISSUE TITLE
remote hung up unexpectedly (git modules)

### ISSUE THREAD

**Issue by replikation** [seqeralabs/nf-tower#329]
Hi,

when running a workflow via tower's launchpad I get a `remote hung up unexpectedly` exit `9` error, when tower tries to pull a private git submodule.  Both the workflow git and the attached git submodule are private gits. The github access token works fine if i run it locally (nextflow run username/gitrepo ...) - so the access rights are there.

The full exit via tower:
```
 Workflow execution completed unsuccessfully

The workflow execution failed to start. Exit status: 9

Execution failed: generic::failed_precondition: while running "nf-workflow-2GvbbCnw8sVSRn": unexpected exit status 1 was not ignored

N E X T F L O W  ~  version 21.09.1-edge
Pulling replikation/workflow ...
git@github.com:replikation/repo_module.git: remote hung up unexpectedly
```

when searching on how to resolve the issue I only get git configuration suggestions like these:

```
export GIT_HTTP_MAX_REQUEST_BUFFER=100M
git config --global http.postBuffer 100000000
```

I tried adding this to the Pre-run script but then I get to exit 127 and it's not even pulling the repo. So I don't really know what might cause the hung-up error (e.g. tower or something else).

**Comment by replikation** [comment]
````
org.eclipse.jgit.errors.UnsupportedCredentialItem: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$YesNoType:The authenticity of host 'github.com' can't be established.
````

**Comment by abhi18av** [comment]
Hi @replikation ,

Apologies for the inconvenience, however the use of sub-modules is not supported on Tower at the moment.

**Comment by replikation** [comment]
@abhi18av 
Hi, thanks for the response. The error is related to using ssh protocol in the `.gitmodules`  file. So changing from e.g. `url = git@github.com:` to `url = https://github.com/....` resolved this issue and tower works with git modules.

On my end, the issue can be closed. Might be useful if your tower either reports that or automatically changes the ssh to HTTPS :)

best and thanks

**Comment by abhi18av** [comment]
Thanks for letting us know @replikation ! 

I'll take this up internally and would circle back if we have updates. Closing the issue for the time being.
