### ISSUE TITLE
Login button opens new tab unnecessarily

### ISSUE THREAD

**Issue by MillironX** [seqeralabs/nf-tower#334]
## Steps to Reproduce

1. In a new browser window, navigate to https://tower.nf
2. Click the "Login" button in the top-right corner

## Expected Behavior

The browser navigates to the login page, and then to my Tower dashboard

## Actual Behavior

The browser opens a new tab, and that tab navigates to login, and then to my Tower dashboard

## Context

Opening new browser windows on users has been considered impolite for over two decades now: https://www.nngroup.com/articles/the-top-ten-web-design-mistakes-of-1999/. In this instance, it is even more annoying because

1. The dashboard url and the "landing page" url are the exact same
2. I am automatically logged out of Tower so frequently (~every 3 hrs, but I haven't timed it)

Which means I tend to think I'm going directly to my dashboard, but will be forced into opening a new tab, instead.

## Suggested Solution

Remove the `target="_blank"` attribute from the login button on the main screen.

**Comment by evanfloden** [comment]
This is now resolved. Thanks for reporting.
