### ISSUE TITLE
Zombie runs, redux: Jobs still shown as running

### ISSUE THREAD

**Issue by lina-kim** [seqeralabs/nf-tower#354]
Hi all,

First, thanks for creating and maintaining Nextflow Tower! I've been using it since it was in beta, and am a big fan.

I recently had an issue identical to #313: A number of previously killed jobs (15 in all) are still marked active on my dashboard, some apparently active for three weeks. All were launched and killed from the command line. Active tasks are labeled either aborted or running, with no exit codes.

![Screenshot 2022-05-18 at 10 36 00](https://user-images.githubusercontent.com/25010133/168995804-81923b63-d8b2-4e20-95e9-0c4f2a9f12c5.png)

This isn't something I've seen in previous releases, so figured I'd bring this up. Thanks!

**Comment by telatin** [comment]
I have the same issue of "zombie" runs. Sometimes runs that didn't even start (e.g. failed to locate input reads) but all appear and cannot be deleted due to being ongoing.

![mag](https://user-images.githubusercontent.com/15690844/173828574-63eb293f-52ec-40a3-a3fa-76404fe271ed.png)
g

**Comment by lina-kim** [comment]
Most are now terminated - thanks @pditommaso!
